name: docker-image

on:
  workflow_run:
    branches:
      - main
    workflows:
      - code-review
    types:
      - completed

env:
  REGISTRY: ghcr.io
  USER: ${{ github.actor }}
  PASS: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Auth with Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build & push Docker image
        uses: docker/build-push-action@v2
        with:
          file: .docker/node/Dockerfile
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
